%%%%%%%%%% AUV path planning using GA %%%%%%%%%%
%%%%%Run 'RP_coordinate.m' before running main %%%%

clear all;
close all;
tic;%Runtime timer
%% global variables

load ('coor.mat');   %Load data generated by RP_coordinate.m

Popsize =50;         %Population size, should be an even integer

%Genetic parameters
%MIXRATE = 0.3;
ITERATION = 10000;   %Number of iteration
THRESHOLD = 100;
Pcross = 0.7;       %Crossover rate
Pmutation = 0.3;    %Mutation rate

%Begin
Parentpop=InitPop(Popsize,RPNUM,adjacency);
Fitnesscurve=[];
Generation = 1; 

Fitconst=0;         %Number of generations that fitness values remain constant
%% Genetic algorithm
while(Generation <= ITERATION)
    if (Fitconst<=THRESHOLD) %Stop iteration if fitness value is constant in threshold number of genreations
        fitness = Fitness(Parentpop,adjacency);       %Calculate fitness of parents
        crossover = Crossover(Parentpop,Pcross);      %Crossover
        Childpop = Mutation(crossover,Pmutation);     %Mutate and get chindren
        combopop=[Parentpop;Childpop];                %Combine parents and chindren
        combofitness=Fitness(combopop,adjacency);       %Calculate overall fitness
        nextpop=Select(combopop,combofitness);        %Select the first half of best to get 2nd gen
        Parentpop=nextpop.pop;
        if(Generation ==1)
            Best_GApath=Parentpop(1,:);
            Best_Fitness=combofitness(nextpop.bestplan);
        else
            New_Best_Fitness=combofitness(nextpop.bestplan);%Evaluate best solution
            New_Best_GApath=Parentpop(1,:);
            
            if(New_Best_Fitness<Best_Fitness)
                Best_Fitness=New_Best_Fitness;
                Best_GApath=New_Best_GApath;
                Fitconst = 0;
                
                %%%%%%%%Visualize planning process%%%%%%%%
%                     GENERATION=[1:Generation-1];
%                     GAplancoor = [RP(Best_GApath).x;RP(Best_GApath).y; RP(Best_GApath).z].';
%                     figure(1);
%                     for i=1:RPNUM
%                         subplot(2,1,1);     %Plot all rendezvous points
%                         plot3(RP(i).x,RP(i).y,RP(i).z,'o');
%                         text(RP(i).x,RP(i).y, RP(i).z,num2str(i));
%                         hold on;
%                         subplot(2,1,2);
%                         plot(RP(i).x,RP(i).y,'o');
%                         text(RP(i).x,RP(i).y,num2str(i));
%                         hold on;
%                     end
%                     subplot(2,1,1);
%                     plot3(GAplancoor(:,1),GAplancoor(:,2),GAplancoor(:,3),'r-.');
%                     title('3D Path of AUV');
%                     grid on;
%                     hold off;
%                     subplot(2,1,2);
%                     plot(GAplancoor(:,1),GAplancoor(:,2),'r-.');
%                     title('2D Path of AUV');
%                     grid on;
%                     hold off;
                %%%%%%%%Visualize planning process%%%%%%%%
                
            else
                Fitconst=Fitconst+1;
            end
        end
        
        Fitnesscurve(Generation)=Best_Fitness;
    
    else
        
        break
        
    end
    
    Generation = Generation +1;
    
end

Best_GApath(RPNUM+1)=Best_GApath(1); %Add the path from end to start
GENERATION=[1:Generation-1];
toc;
%% plot result plan
 GAplancoor = [RP(Best_GApath).x;RP(Best_GApath).y; RP(Best_GApath).z].';
        figure(1);
        for i=1:RPNUM
        subplot(2,1,1);     %Plot all rendezvous points
        plot3(RP(i).x,RP(i).y,RP(i).z,'o');
        text(RP(i).x,RP(i).y, RP(i).z,num2str(i));
        hold on;
        subplot(2,1,2);
        plot(RP(i).x,RP(i).y,'o');
        text(RP(i).x,RP(i).y,num2str(i));
        hold on;
        end
        subplot(2,1,1);
        plot3(GAplancoor(:,1),GAplancoor(:,2),GAplancoor(:,3),'r-.');
        title('3D Path of AUV');
        grid on;
        subplot(2,1,2);
        plot(GAplancoor(:,1),GAplancoor(:,2),'r-.');
        title('2D Path of AUV');
        grid on;
 %% Plot iteration of fitness
 figure(2);
 plot(GENERATION,Fitnesscurve,'r.-');
 title('Minimum distance in each generation');
 xlabel('Generation');
 ylabel('Fitness value');
 legend('Best Fitness Value');
 set(gca, 'Fontname', 'Times New Roman', 'FontSize', 14);
 grid on;
 
